notifications:
  slack: cuencafinance:J6Mt565Z5Kr3w6chZjPo563x

language: dart

jobs:
  include:
    - stage: code coverage
      install: pub global activate dart_coveralls
      script:
      -  dart_coveralls report --token=CLABE_DART_COVERALLS_TOKEN test/clabe_test.dart