notifications:
  slack: cuencafinance:Vb7c4Zn7YCpT0wGjOFDwYQUM

language: dart

jobs:
  include:
    - stage: code coverage
      install: pub global activate dart_coveralls
      script:
      -  dart_coveralls report --token=CLABE_DART_COVERALLS_TOKEN test/clabe_test.dart