name: clabe_dart
description: Validate a CLABE in Mexico.
version: 1.0.0
author: Cuenca <dev@cuenca.com>
homepage: https://github.com/cuenca-mx/clabe-dart

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  dart_coveralls: ^0.6.0

dev_dependencies:
  test: ^1.5.1+1
