name: clabe_dart
description: Validate a CLABE (Clave Bancaria Estandarizada), calculate the control digit and get the name of the bank.
version: 1.1.4
author: Cuenca <dev@cuenca.com>
homepage: https://github.com/cuenca-mx/clabe-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:

dev_dependencies:
  test: ^1.5.1+1
  dart_coveralls:
    git:
      ref: master
      url: git@github.com:mike-one/dart-coveralls.git
