name: clabe-dart
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# author: Gregorio Castro <gregorio@cuenca.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
