name: clabe_dart
description: Validate a CLABE (Clave Bancaria Estandarizada), calculate the control digit and get the name of the bank.
version: 1.2.0
homepage: https://github.com/cuenca-mx/clabe-dart

environment:
  sdk: ">=3.3.4 <4.0.0"

#dependencies:

dev_dependencies:
  test: ^1.5.1+1
