name: clabe_dart
description: Validate a CLABE (Clave Bancaria Estandarizada), calculate the control digit and get the name of the bank.
version: 1.1.2
author: Cuenca <dev@cuenca.com>
homepage: https://github.com/cuenca-mx/clabe-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

#dependencies:

dev_dependencies:
  test: ^1.5.1+1
  dart_coveralls: ^0.6.0+4
