name: Dart

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: 2.15.0
      - name: Install dependencies
        run: dart pub get
      - name: Lint
        run: dart format --output=none --set-exit-if-changed .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: 2.15.0
      - name: Install dependencies
        run: |
          dart pub get
          dart pub global activate coverage
      - name: Tests
        run: |
          dart pub global run coverage:test_with_coverage
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
          fail_ci_if_error: true
